### ISSUE TITLE
how to use this tool?

### ISSUE THREAD

**Issue by crazysvn** [Cosium/matrix-communication-client#19]
looks like the test sample don't work to login ?

**Comment by reda-alaoui** [comment]
Looking at https://github.com/Cosium/matrix-communication-client/issues/20, it seems you fixed your issue?

**Comment by crazysvn** [comment]
> 

yes, I can use it now. thanks your make this good tool.
only thing is, it seems can't read encrypted message, while when I use the same account on element, it can. maybe there's still some trick I didn't get. I now just set the room not encrypted, and can read everything.
