### ISSUE TITLE
sending message issue

### ISSUE THREAD

**Issue by crazysvn** [Cosium/matrix-communication-client#20]
I'm trying to use a java client named matrix-communication-client to send message, but always get an 403, any ideas? looks like it login successfully, the roomId is also correct, I think.
![image](https://github.com/Cosium/matrix-communication-client/assets/26742593/21bea3a5-e375-4c6c-806b-bcf7ab97a446)

**Comment by crazysvn** [comment]
fixed. just simply because of wrong roomId. now I can send message!

**Comment by reda-alaoui** [comment]
👍
